---
# we removed the following modules from our modulesync_config / hide it because they are not
# Puppet modules but match the puppet- pattern
# The modules in the list are broken, unfinished or got migrated
# (yes, that really happens from time to time)
# ToDo: extend this list with repos that are archived on github
# ToDo: Archive repos that we migrate away
legacy_or_broken_nobody_knows:
  - puppet-bacula
  - puppet-nagios_providers
  - puppet-iis
  # Actually a gem
  - puppet-syntax
  - puppet-blacksmith
  # Actually an emacs plugin
  - puppet-mode

# define some versions that we want to match against
puppet_support_range: ">= 5.5.8 < 7.0.0"

# Updates here probably also need an update here: config/locales/*.yml
support_ranges:
  ubuntu:
    - "16.04"
    - "18.04"
    - "20.04"
  debian:
    - 8
    - 9
    - 10
  centos:
    - 6
    - 7
    - 8
  freebsd:
    - 11
    - 12
  fedora:
    - 30
    - 31
    - 32

# labels that we would like to have on all repositories
labels:
  - name: backwards-incompatible
    color: eb6420
    aliases:
      - backwards-incompatible
      - breaking
      - breaking-change
  - name: beginner-friendly
    color: d4c5f9
    aliases:
      - beginner
      - beginner friendly
  - name: bug
    description: "Something isn't working"
    color: 0e8a16
    aliases:
      - bug
      - bugfix
  - name: docs
    description: "Improvements or additions to documentation"
    color: 006b75
    aliases:
      - docs
      - documentation
  - name: duplicate
    description: "This issue or pull request already exists"
    color: cccccc
    aliases:
      - duplicate
  - name: enhancement
    description: "New feature or request"
    color: 0052cc
    aliases:
      - enhancement
      - feature
  - name: modulesync
    color: fbca04
    aliases:
      - msync
  - name: needs-docs
    color: 006b75
    aliases:
      - needs-docs
  - name: needs-feedback
    description: "Further information is requested"
    color: 5319e7
    aliases:
      - feedback
      - feedback-needed
      - needs-feedback
      - question
  - name: needs-help
    description: "Extra attention is needed"
    color: d4c5f9
    aliases:
      - help
      - help wanted
      - needs-help
      - help-wanted
  - name: needs-rebase
    color: 207de5
    aliases:
      - needs-rebase
      - rebaseneeded
      - rebase
  - name: needs-squash
    color: c2e0c6
    aliases:
      - needs-squash
      - squash
  - name: needs-tests
    color: f7c6c7
    aliases:
      - needs-tests
      - tests
  - name: needs-work
    description: "not ready to merge just yet"
    color: fbca04
    aliases:
      - in progress
      - needs-work
  - name: tests-fail
    color: e11d21
    aliases:
      - tests-fail
  - name: wont-fix
    description: "This will not be worked on"
    color: "000000"
    aliases:
      - wontfix
      - wont-fix
      - won't-fix
  - name: skip-changelog
    color: 343e4c
    aliases:
      - changelog
  - name: release-summary
    color: bfdadc
    aliases:
      - release-summary
  - name: "good first issue"
    description: "Good for newcomers"
    color: 7057ff
  - name: invalid
    description: "This doesn't seem right"
    color: e4e669

teams_with_admin_access:
  - org-login: voxpupuli
    team-slug: project-maintainers
